name:
  neutral-farming

services:
  postgres:
    container_name: neutral-farming-db
    image: postgres:17.1-alpine
    restart: unless-stopped
    ports:
      - "${EXTERNAL_DB_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/data/postgres
      - TZ=America/Lima
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgresql:/data/postgres
      - postgresql_lib:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
  api:
    container_name: neutral-farming-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
      - "${EXTERNAL_API_PORT}:8080"
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    restart: unless-stopped
  migrate:
    image: migrate/migrate
    profiles: ["tools"]
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
      - ./scripts:/scripts
#    environment:
#    command:
#      [
#        "-path", "/migrations",
#        "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=${DB_SSL_MODE}",
#        "up"
#      ]
#    entrypoint: ["/bin/sh", "/scripts/migrate.sh"]

volumes:
  postgresql:
  postgresql_lib:
  postgresql_data: